dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: ${{ secrets.DB_HOST }}
      user: ${{ secrets.DB_USER }}
      password: ${{ secrets.DB_PASSWORD }}
      port: ${{ secrets.DB_PORT }}
      dbname: ${{ secrets.DB_NAME }}
      schema: raw
      threads: 1