name: 'lokesh_project'
version: '1.0.0'
 
profile: 'lokesh_project'
 
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
 
clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  lokesh_project:
    staging:
      +schema: staging_lok
      +materialized: incremental
    marts:
      +schema: marts_lok
      +materialized: table